version: "3.8"

services:
  # Zookeeper service
  zoo1:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - kafka_network

  # Kafka service
  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181" # Ensure this is pointing to the correct Zookeeper hostname
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Add JMX Exporter for Prometheus
      KAFKA_OPTS: "-javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=7071:/usr/share/jmx-exporter/kafka-broker.yml"
    volumes:
      - ./jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar # Ensure this file exists locally and is not a directory
      - ./jmx_exporter/kafka-broker.yml:/usr/share/jmx-exporter/kafka-broker.yml # Optional: If you have a configuration file for Kafka exporter
    depends_on:
      - zoo1
    networks:
      - kafka_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount Prometheus config
    networks:
      - kafka_network # Ensuring the correct network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # Streamlit App (Main Application for monitoring)
  streamlit_app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - kafka1
    command: streamlit run /app/streamlit_app/app.py
    networks:
      - kafka_network

  # Grafana service for real-time visualization
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hadesarchitect-kafka-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - kafka1
    networks:
      - kafka_network

  # InfluxDB service
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086" # Exposes InfluxDB UI and API
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpassword
      INFLUXDB_DB: air_quality_data
    volumes:
      - influxdb_data:/var/lib/influxdb # Persist data
    networks:
      - kafka_network
  # Air Quality Exporter service
  air_quality_exporter:
    build: ./air_quality_exporter # Path to your air_quality_exporter directory
    ports:
      - "8000:8000" # Exposing metrics on port 8000
    depends_on:
      - postgres # Ensuring that the exporter starts only after PostgreSQL is up
    networks:
      - kafka_network

  # PostgreSQL (Optional, for storing historical air quality data)
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: air_quality_user
      POSTGRES_PASSWORD: air_quality_password
      POSTGRES_DB: air_quality_db
    ports:
      - "5433:5432"
    networks:
      - kafka_network

volumes:
  grafana_data:
  influxdb_data:
  postgres_data:

networks:
  kafka_network:
    driver: bridge
